# Generated by Django 2.1.1 on 2018-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='FinishDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
